package user.controller;

import user.dao.UserDao;
import user.dto.User;

public class UserController {
	
	public static void main(String[] args) {
		
		
		
//		Autogenerated ID
		
//		User user = new User();
//		user.setAddress("Jalgaon");
//		user.setName("Patizvzdl");
//		
//		UserDao dao= new UserDao();
//		dao.saveUser(user);
		

		User user = new User();
		user.setAddress("Jalgaon");
		user.setName("Patizvzdl");
		
		UserDao dao= new UserDao();
		dao.saveUser(user);
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
//		-------------------------------------------------------------------------
		
//	    User user=new User();
//	    
//		user.setId(111);
//		user.setName("Rajj");
//		user.setAddress("Aet");
//		
//		UserDao userDao =new UserDao() ;
//		userDao.saveUser(user);
//		
//		

//		//object
//		UserDao userDao=new UserDao();
		
		//find user 
//		userDao.findUser(4);
//		
		//DeleteUser
//		userDao.deleteUser(400);
		
		//Update 2

//		User user=new User();
//		user.setId(44);
//		user.setName("Manish");
//		user.setAddress("Channai");
//		
//		UserDao userDao=new UserDao();
//		userDao.updateUser(4,user);
//		
//		
		
//		User user=new User();		
//		user.setName("chetana");
//		user.setAddress("Gao");
//		
//		UserDao userDao=new UserDao();
//		userDao.updateUser(4,user);
		
		
		
	}

}
